[package]
name = "modulart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
iced = { version = "0.9.0", features=["canvas"]}
itertools = "0.10.5"
rustc-hash = "1.1.0"
